### PR TITLE
Now selecting template via `tempate_name` works

### PR DESCRIPTION
**Pull request by histrio**
Tehere was error when template_name defined:
undefined method `context' for #<Fog::Compute::OpenNebula::Flavors:0x00000002da6a40>
/root/.vagrant.d/gems/gems/opennebula-provider-1.1.0/lib/opennebula-provider/helpers/fog.rb:53:in
`compute'

### CODE REVIEW

**Comment by eucher** [comment]
It is undocumented function :) Please fix Readme too.

What if there are multiple templates with same name, .first will select newest?

**Comment by histrio** [comment]
Hi @eucher !
In my case it pretty rare case when templates have same name. Anyway, by default fog's flavors list is ordered by id so selecting the last one would give us the most recent template with that name.

**Comment by eucher** [comment]
What if template with same name exist for multiple users or groups, without access to each other. It must use templates according to user scope only. Can you check it?

**Comment by histrio** [comment]
I just checked it: each user saw only their scope.

**Pull request merged**
